services: # 컨테이너 설정 정보

  mysql:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # 루트 비밀번호 설정
      MYSQL_DATABASE: ${MYSQL_DATABASE}               # 기본 데이터베이스 이름
      MYSQL_USER: ${MYSQL_USER}                 # 사용자 이름
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}         # 사용자 비밀번호
    ports:
      - "3306:3306"                        # 호스트와 컨테이너의 포트 매핑
    volumes:
      - mysql_data:/var/lib/mysql          # 데이터 볼륨 설정

  backend:
    container_name: gaji-server
    image: ${GAJI_SERVER_IMAGE}
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8080:8080

volumes:
  mysql_data:                      # mysql_data 볼륨 정의